package com.auction.network;

public enum MessageType {
    LOGIN, LOGIN_RESPONSE,
    REGISTER, REGISTER_RESPONSE,
    GET_AUCTIONS, AUCTIONS_RESPONSE,
    PLACE_BID, BID_RESPONSE,
    BID_UPDATE,
    CREATE_ITEM, CREATE_ITEM_RESPONSE,

    UPDATE_ITEM, UPDATE_ITEM_RESPONSE,

    CREATE_AUCTION, CREATE_AUCTION_RESPONSE,
    END_AUCTION, CANCEL_AUCTION, ADMIN_CANCEL_AUCTION,
    MARK_PAID, MARK_PAID_RESPONSE,
    DEPOSIT, DEPOSIT_RESPONSE,
    SETUP_AUTOBID, SETUP_AUTOBID_RESPONSE,
    START_AUCTION, START_AUCTION_RESPONSE,
    ERROR
}